sonar.projectKey=GabrielMainiere_go-api-cicd
sonar.projectName=go-api-cicd
sonar.organization=gabrielmainiere
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
